.TH hustle-solve 1 "20 August 2022" "version 1.3.1" "User Commands"
.SH NAME
hustle-solve \- Solve a given state
.SH SYNOPSIS
hustle solve [GAMESTATE] [FLAGS] [OPTIONS]
.SH ARGS
.PP
\fB<GAMESTATE>\fR
.RS 4
The gamestate to solve [default: initial state].
Can end with or without a specified last guess [example: salet.bbygb, lodge.bbyby.triad]\&.
.RE
.SH FLAGS
.SS BASIC
.PP
\fB--hard\fR
.RS 4
Treat as a 'hard mode' game (hints must be reused).
.RE
.PP
\fB-h\fR, \fB--help\fR
.RS 4
Print a synopsis for this command.
.RE
.SS TABLES
\fB-a\fR, \fB--alist\fR
.RS 4
Display a table of potential answers at GAMESTATE.
.RE
.PP
\fB-g\fR, \fB--glist\fR
.RS 4
Display a table of top guesses at GAMESTATE if no last guess specified.
.RE
.PP
\fB-f\fR, \fB--flist\fR
.RS 4
Display a table of potential feedbacks at GAMESTATE if last guess specified.
.RE
.SH OPTIONS
.SS BASIC
.PP
\fB-b\fR, \fB--wbank\fR <\fIWBP\fR>
.RS 4
Specify the word bank file to use [default: \fI/usr/share/hustle/bank1.csv\fR,
wordle's standard word bank]. Hellowordl's word bank is also included on installation
at \fI/usr/share/hustle/bank2.csv\fR.
.RE
\fB-l\fR, \fB--wlen\fR <\fIWLEN\fR>
.RS 4
Specify the word length to use [default: 5].
.RE
.PP
\fB-o\fR, \fB--dt\fR <\fIDT\fR>
.RS 4
Output decision tree to \fIDT\fR.
.RE
\fB-f
.SS PARAMETERS
.PP
\fB-e\fR, \fB--ecut\fR <\fIECUT\fR>
.RS 4
Specify the maximum number of remaining answers to treat as an 'endgame' [default: 15]
.RE
.PP
\fB-M\fR, \fB--ncacherows\fR <\fINCACHEROWS\fR>
.RS 4
Specify the number of cache rows to use [default: 64].
.RE
.PP
\fB-N\fR, \fB--ncachecols\fR <\fINCACHECOLS\fR>
.RS 4
Specify the number of cache columns to use [default: 16].
.RE
.PP
\fB-m\fR, \fB--ntops1\fR <\fINTOPS1\fR>
.RS 4
Specify the number of top soft heuristic words to try [default: 1500].
.RE
.PP
\fB-n\fR, \fB--ntops2\fR <\fINTOPS2\fR>
.RS 4
Specify the number of top hard heuristic words to try [default: 15].
.RE
.PP
\fB-t\fR, \fB--turns\fR <\fITURNS\fR>
.RS 4
Specify the maximum number of turns to solve in [default: 6].
.SH "SEE ALSO"
.sp
\fBhustle\fR(1), \fBhustle-play\fR(1), \fBhustle-gen\fR(1)

