.TH hustle-lgen 1 "1 August 2022" "version 1.3.0" "User Commands"
.SH NAME
hustle-lgen \- Generate heuristic data
.SH SYNOPSIS
hustle hgen <NITER> <OUT> [--ecut <ECUT>] [-h | --help] [--hdp <HDP>]
[--ntops1 <NTOPS1>] [--ntops2 <NTOPS2>] [--wbp <WBP>] [--wlen <WLEN>]
.SH ARGS
.PP
\fB<NITER>\fR
.RS 4
The number of data points to generate\&.
.RE
.PP
\fB<OUT>\fR
.RS 4
The file to output data to\&.
.RE
.SH OPTIONS
.PP
\fB--alist\fR
.RS 4
List the potential answers.
.RE
.PP
\fB--ecut\fR <\fIECUT\fR>
.RS 4
Specify the maximum number of remaining answers to treat as an 'endgame' [default: 15]
.RE
.PP
\fB-h\fR, \fB--help\fR
.RS 4
Print a synopsis for this command\&.
.RE
.PP
\fB--hdp\fR <\fIHDP\fR>
.RS 4
Specify the heuristic file to use [default: \fI/usr/share/hustle/happrox.csv\fR].
.RE
.PP
\fB--ldp\fR <\fILDP\fR>
.RS 4
Specify the lower bounds file to use [default: \fI/usr/share/hustle/lbounds.csv\fR].
.RE
.PP
\fB--ntops1\fR <\fINTOPS1\fR>
.RS 4
Specify the number of top soft heuristic words to try [default: 1000].
.RE
.PP
\fB--ntops2\fR <\fINTOPS2\fR>
.RS 4
Specify the number of top hard heuristic words to try [default: 10].
.RE
.PP
\fB--turns\fR <\fITURNS\fR>
.RS 4
Specify the maximum number of to solve in [default: 6].
.RE
.PP
\fB--wbp\fR <\fIWBP\fR>
.RS 4
Specify the word bank file to use [default: \fI/usr/share/hustle/bank1.csv\fR,
wordle's standard word bank]. Hellowordl's word bank is also included on installation
at \fI/usr/share/hustle/bank2.csv\fR\&.
.RE
.PP
\fB--wlen\fR <\fIWLEN\fR>
.RS 4
Specify the word length to use\&.
Defaults to 5\&.
.SH "SEE ALSO"
.sp
\fBhustle\fR(1), \fBhustle-play\fR(1), \fBhustle-hgen\fR(1), \fBhustle-ggen\fR(1), \fBhustle-lgen\fR(1)

