.TH hustle-ggen 1 "1 August 2022" "version 1.3.0" "User Commands"
.SH NAME
hustle-ggen \- Generate general data
.SH SYNOPSIS
hustle ggen [--alens] [--ecut <ECUT>] [--elist] [-h | --help] [--hdp <HDP>]
[--ntops1 <NTOPS1>] [--ntops2 <NTOPS2>] [--turns <TURNS>]
[--wbp <WBP>] [--wlen <WLEN>]
.SH ARGS
.PP
\fB<NITER>\fR
.RS 4
The number of data points to generate\&.
.RE
.PP
\fB<OUT>\fR
.RS 4
The file to output data to\&.
.RE
.SH OPTIONS
.PP
\fB--alens\fR <\fIALENS\fR>
.RS 4
Specify the range of answer lengths to try [default: all].
.RE
.PP
\fB-h\fR, \fB--help\fR
.RS 4
Print a synopsis for this command\&.
.RE
.PP
\fB--hdp\fR <\fIHDP\fR>
.RS 4
Specify the heuristic file to use [default: \fI/usr/share/hustle/happrox.csv\fR].
.RE
.PP
\fB--ntops1\fR <\fINTOPS1\fR>
.RS 4
Specify the range of top soft heuristic words to try [default: 1..=1000].
.RE
.PP
\fB--ntops2\fR <\fINTOPS2\fR>
.RS 4
Specify the range of top hard heuristic words to try [default: 1..=10].
.RE
.PP
\fB--turns\fR <\fITURNS\fR>
.RS 4
Specify the range of maximum numbers of turns to solve in [default: 1..=6].
.RE
.PP
\fB--wbp\fR <\fIWBP\fR>
.RS 4
Specify the word bank file to use [default: \fI/usr/share/hustle/bank1.csv\fR,
wordle's standard word bank]. Hellowordl's word bank is also included on installation
at \fI/usr/share/hustle/bank2.csv\fR\&.
.RE
.PP
\fB--ldp\fR <\fILDP\fR>
.RS 4
Specify the lower bounds file to use [default: \fI/usr/share/hustle/lbounds.csv\fR].
.RE
.PP
\fB--wlen\fR <\fIWLEN\fR>
.RS 4
Specify the word length to use\&.
Defaults to 5\&.
.SH "SEE ALSO"
.sp
\fBhustle\fR(1), \fBhustle-play\fR(1), \fBhustle-hgen\fR(1), \fBhustle-ggen\fR(1), \fBhustle-lgen\fR(1)

