.TH hustle 1 "1 August 2022" "version 1.3.0" "User Commands"
.SH NAME
hustle \- A wordle clone and solver, geared towards speedrunning
.SH SYNOPSIS
hustle [-V | --version] [-h | --help] <COMMAND> [<ARGS>]
.SH OPTIONS
.TP
\fB\-V\fR  \fB\-\-version\fR
Prints the version of hustle\&.
.TP
\fB\-h\fR  \fB\-\-help\fR
Prints the synopsis of how to use hustle\&.
.SH GENERAL COMMANDS
.TP
\fBhustle-play\fR(1)
Opens the TUI for playing hustle\&.
.TP
\fBhustle-solve\fR(1)
Solve a given state\&.
.SH MISCELLANEOUS COMMANDS
.TP
\fBhustle-hgen\fR(1)
Generate heuristic data\&.
.TP
\fBhustle-ggen\fR(1)
Generate general analysis data\&.
.TP
\fBhustle-lgen\fR(1)
Generate lower bounds data\&.
.SH "SEE ALSO"
.sp
\fBhustle\fR(1), \fBhustle-play\fR(1), \fBhustle-hgen\fR(1), \fBhustle-ggen\fR(1), \fBhustle-lgen\fR(1)

